version: '3'
services:
  client:
    # image to build container from 
    image: node:16
    container_name: geography_client
    # expose a container port to a local port 
    ports:
      - 8080:8080
    # where is the code and shall we access it?
    volumes:
      - type: bind
        source: ./geography_client
        target: /code
    working_dir: /code # Corrected indentation and syntax
    # what to do once the container has started 
    command: bash -c "npm install && npm run dev"
    depends_on:
      - api

  api:
    # pick an image?
    image: node:18
    container_name: geography_server
    # do we nned to expose ports?
    ports:
      - 3000:3000
    # where does the code live?
    volumes:
      - type: bind
        source: ./geography_server
        target: /code
    working_dir: /code # what dto do once the container is up and running?
    command: bash -c "npm install && npm run dev"
